services:
  postgres:
    image: postgres:15-alpine
    container_name: pokemon_ev_db
    environment:
      POSTGRES_DB: pokemon_ev
      POSTGRES_USER: trainer
      POSTGRES_PASSWORD: pikachu123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trainer -d pokemon_ev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
